# Generated by Django 4.1.3 on 2022-11-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HourlyObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("time", models.DateTimeField()),
                ("temperature_2m", models.FloatField()),
                ("apparent_temperature", models.FloatField()),
                ("apparent_diff", models.FloatField()),
                ("daily_max", models.FloatField()),
                ("daily_min", models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="hourlyobservation",
            constraint=models.UniqueConstraint(
                fields=("lat", "lon", "time"), name="unique_observation_per_time_and_location"
            ),
        ),
    ]
